concurrent = 10
check_interval = 3
shutdown_timeout = 30

[[runners]]
  url = "${GITLAB_EXTERNAL_URL}"
  token = "${RUNNER_DOCKER_AUTH_TOKEN}"
  executor = "docker"
  output_limit = 8192
  limit = 10
  request_concurrency = 5
  cache_dir = "/cache"
  [runners.docker]
    tls_verify = false
    image = "bwc/jdk:21"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    pull_policy = "if-not-present"
    allowed_pull_policies = ["if-not-present", "never"]
    allowed_images = [
      "bwc/*:*"
    ]
    allowed_services = []
    cap_drop = ["ALL"]
    security_opt = ["no-new-privileges:true"]
